### PR TITLE
add template for student hackathon projects

### PR DESCRIPTION
**Pull request by andrej**

### CODE REVIEW

**Comment by vikhyatg** [comment]
Should the template notebook be part of a "model" folder?

**Comment by andrej** [comment]
Why? It's not a model.

But I don't mind either way

**Comment by vikhyatg** [comment]
The thought behind was ease of navigation.  
1) As the intention of this template is to help students use any model which we provide in the "models" folder, 
it seems the first place to look for help on how to use them will be in that folder. 
2) Helps us declutter the top level of the repo.

Feel free to move it out of "models" if you think it is not just for helping with model use.

**Comment by andrej** [comment]
Ah yes that works. Thanks for clarifying

**Comment by andrej** [comment]
I actually ended up moving this to yet another new folder "hackathon" in #67, which adds the seed project. That way hackathon related stuff is grouped together and the models folder only contains xmodels.

**Pull request merged**
